namespace Machine.Core;

public sealed record MachineLearningPersistedState(
    int SchemaVersion,
    IReadOnlyList<MachineLearningBaselineState> Baselines,
    IReadOnlyList<MachineLearningEpisode> Episodes,
    long ObservationCount,
    DateTimeOffset? FirstObservedAt,
    DateTimeOffset? LastObservedAt,
    DateTimeOffset? PersistedAt = null,
    long ObservedDurationTicks = 0,
    MachineLearningEpisode? ActiveEpisode = null,
    MachineLearningMetadataState? Metadata = null,
    IReadOnlyList<MachineLearningContextProfile>? ContextProfiles = null,
    IReadOnlyList<MachineLearningRecurringPattern>? BroaderPatterns = null);

public sealed record MachineLearningMetadataState(
    long LifetimeAcceptedObservationCount,
    long LifetimeObservedDurationTicks,
    long LifetimeMachineSessionCount,
    DateTimeOffset? FirstLearningAt,
    DateTimeOffset? LastLearningAt,
    DateTimeOffset CurrentSessionStartedAt,
    DateTimeOffset? PreviousMachineSessionEndedAt,
    DateTimeOffset? LastPersistedAt);

public sealed record MachineLearningBaselineState(
    int LocalHour,
    MachineUserActivityState ActivityState,
    long SampleCount,
    double CpuMean,
    double CpuM2,
    double MemoryMean,
    double MemoryM2,
    DateTimeOffset FirstObservedAt,
    DateTimeOffset LastObservedAt,
    IReadOnlyList<DateOnly>? ObservedLocalDates = null,
    long NetworkQuietSampleCount = 0,
    long NetworkLightSampleCount = 0,
    long NetworkActiveSampleCount = 0,
    long NetworkUnavailableSampleCount = 0,
    int ObservedDayCount = 0,
    DateOnly? LastObservedLocalDate = null,
    long ObservedDurationTicks = 0,
    double? AdaptiveCpuMean = null,
    double? AdaptiveCpuVariance = null,
    double? AdaptiveMemoryMean = null,
    double? AdaptiveMemoryVariance = null,
    long AdaptiveSampleCount = 0,
    DateTimeOffset? AdaptiveLastUpdatedAt = null,
    long EstimatedWallPowerSampleCount = 0,
    double? EstimatedWallPowerMeanWatts = null,
    double? EstimatedWallPowerM2 = null,
    int EstimatedWallPowerObservedDayCount = 0,
    DateOnly? EstimatedWallPowerLastObservedLocalDate = null,
    DateTimeOffset? EstimatedWallPowerFirstObservedAt = null,
    DateTimeOffset? EstimatedWallPowerLastObservedAt = null,
    double? AdaptiveEstimatedWallPowerMeanWatts = null,
    double? AdaptiveEstimatedWallPowerVariance = null,
    long AdaptiveEstimatedWallPowerSampleCount = 0,
    DateTimeOffset? AdaptiveEstimatedWallPowerLastUpdatedAt = null);
